---
parser: babel-eslint
extends: 
  - eslint:recommended
plugins: 
  - react
env: 
  browser: true
  es6: true
  mocha: true
  node: true
ecmaFeatures: 
  jsx: true
  modules: true
rules: 
  comma-dangle: [1, always-multiline]
  eol-last: 1
  indent: [1, 2, { SwitchCase: 1 }]
  jsx-quotes: 1
  keyword-spacing: 1
  no-alert: 1
  no-console: 0
  no-debugger: 1
  no-lone-blocks: 0
  no-spaced-func: 2
  no-trailing-spaces: 1
  no-underscore-dangle: 1
  no-unexpected-multiline: 2
  no-unused-vars: [1, { varsIgnorePattern: "^_", argsIgnorePattern: "^_" }]
  no-var: 1
  quotes: [1, double] 
  react/display-name: [1, { ignoreTranspilerName: false }]
  react/forbid-prop-types: [1, { forbid: ["any"] }]
  react/jsx-boolean-value: 1
  react/jsx-closing-bracket-location: 0
  react/jsx-curly-spacing: 1
  react/jsx-indent-props: 0
  react/jsx-key: 1
  react/jsx-max-props-per-line: 0
  react/jsx-no-bind: 0
  react/jsx-no-duplicate-props: 1
  react/jsx-no-literals: 0
  react/jsx-no-undef: 1
  react/jsx-pascal-case: 1
  react/jsx-sort-prop-types: 0
  react/jsx-sort-props: 0
  react/jsx-uses-react: 1
  react/jsx-uses-vars: 1
  react/jsx-wrap-multilines: 1
  react/no-danger: 1
  react/no-did-mount-set-state: 1
  react/no-did-update-set-state: 1
  react/no-direct-mutation-state: 1
  react/no-multi-comp: [1, { ignoreStateless: true }]
  react/no-unknown-property: 1
  react/prefer-es6-class: 1
  react/prop-types: 1
  react/react-in-jsx-scope: 1
  react/self-closing-comp: 1
  react/sort-comp: 1
  semi: [1, never]
  space-before-blocks: 1
  space-infix-ops: [1, { int32Hint: false }]
  space-unary-ops: 1
globals: 
  CONFIG: true
